version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Nothing to do here"
  build:
    commands:
      - echo "Zipping deployment package..."

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name ec2-report-generator-lambdafunction --zip-file 
      - echo "DONE!!"

